# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forumapp.Question'),
        ),
    ]
